version: '3.9'

services:
  app:
    build: .
    image: ramirezy/flask-cars-app:1.0.1
    container_name: flask_app
    restart: unless-stopped
    env_file:
      - file.env
    ports:
     - 5000:5000
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - file.env
    ports:
     - 3306:3306
    expose:
     - 3306
    volumes:
     - my-db:/var/lib/mysql

volumes:
 my-db:
